package com.github.support.entitement.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class MigrationTask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.TASK_ID
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.TASK_NAME
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.IS_ENABLE
     *
     * @mbggenerated
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.IS_ENABLE_DELETE
     *
     * @mbggenerated
     */
    private Boolean isEnableDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.PROCESSING
     *
     * @mbggenerated
     */
    private Float processing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.LAST_EXCUTE_TIME
     *
     * @mbggenerated
     */
    private Date lastExcuteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.EXT01
     *
     * @mbggenerated
     */
    private String ext01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.EXT02
     *
     * @mbggenerated
     */
    private String ext02;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.EXT03
     *
     * @mbggenerated
     */
    private String ext03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_migration_task.LAST_UPDATE_BY
     *
     * @mbggenerated
     */
    private String lastUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_migration_task
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.TASK_ID
     *
     * @return the value of t_migration_task.TASK_ID
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.TASK_ID
     *
     * @param taskId the value for t_migration_task.TASK_ID
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.TASK_NAME
     *
     * @return the value of t_migration_task.TASK_NAME
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.TASK_NAME
     *
     * @param taskName the value for t_migration_task.TASK_NAME
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.IS_ENABLE
     *
     * @return the value of t_migration_task.IS_ENABLE
     *
     * @mbggenerated
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.IS_ENABLE
     *
     * @param isEnable the value for t_migration_task.IS_ENABLE
     *
     * @mbggenerated
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.IS_ENABLE_DELETE
     *
     * @return the value of t_migration_task.IS_ENABLE_DELETE
     *
     * @mbggenerated
     */
    public Boolean getIsEnableDelete() {
        return isEnableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.IS_ENABLE_DELETE
     *
     * @param isEnableDelete the value for t_migration_task.IS_ENABLE_DELETE
     *
     * @mbggenerated
     */
    public void setIsEnableDelete(Boolean isEnableDelete) {
        this.isEnableDelete = isEnableDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.PROCESSING
     *
     * @return the value of t_migration_task.PROCESSING
     *
     * @mbggenerated
     */
    public Float getProcessing() {
        return processing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.PROCESSING
     *
     * @param processing the value for t_migration_task.PROCESSING
     *
     * @mbggenerated
     */
    public void setProcessing(Float processing) {
        this.processing = processing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.LAST_EXCUTE_TIME
     *
     * @return the value of t_migration_task.LAST_EXCUTE_TIME
     *
     * @mbggenerated
     */
    public Date getLastExcuteTime() {
        return lastExcuteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.LAST_EXCUTE_TIME
     *
     * @param lastExcuteTime the value for t_migration_task.LAST_EXCUTE_TIME
     *
     * @mbggenerated
     */
    public void setLastExcuteTime(Date lastExcuteTime) {
        this.lastExcuteTime = lastExcuteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.EXT01
     *
     * @return the value of t_migration_task.EXT01
     *
     * @mbggenerated
     */
    public String getExt01() {
        return ext01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.EXT01
     *
     * @param ext01 the value for t_migration_task.EXT01
     *
     * @mbggenerated
     */
    public void setExt01(String ext01) {
        this.ext01 = ext01 == null ? null : ext01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.EXT02
     *
     * @return the value of t_migration_task.EXT02
     *
     * @mbggenerated
     */
    public String getExt02() {
        return ext02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.EXT02
     *
     * @param ext02 the value for t_migration_task.EXT02
     *
     * @mbggenerated
     */
    public void setExt02(String ext02) {
        this.ext02 = ext02 == null ? null : ext02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.EXT03
     *
     * @return the value of t_migration_task.EXT03
     *
     * @mbggenerated
     */
    public String getExt03() {
        return ext03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.EXT03
     *
     * @param ext03 the value for t_migration_task.EXT03
     *
     * @mbggenerated
     */
    public void setExt03(String ext03) {
        this.ext03 = ext03 == null ? null : ext03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.LAST_UPDATE_TIME
     *
     * @return the value of t_migration_task.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for t_migration_task.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_migration_task.LAST_UPDATE_BY
     *
     * @return the value of t_migration_task.LAST_UPDATE_BY
     *
     * @mbggenerated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_migration_task.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for t_migration_task.LAST_UPDATE_BY
     *
     * @mbggenerated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_migration_task
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MigrationTask other = (MigrationTask) that;
        return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getTaskName() == null ? other.getTaskName() == null : this.getTaskName().equals(other.getTaskName()))
            && (this.getIsEnable() == null ? other.getIsEnable() == null : this.getIsEnable().equals(other.getIsEnable()))
            && (this.getIsEnableDelete() == null ? other.getIsEnableDelete() == null : this.getIsEnableDelete().equals(other.getIsEnableDelete()))
            && (this.getProcessing() == null ? other.getProcessing() == null : this.getProcessing().equals(other.getProcessing()))
            && (this.getLastExcuteTime() == null ? other.getLastExcuteTime() == null : this.getLastExcuteTime().equals(other.getLastExcuteTime()))
            && (this.getExt01() == null ? other.getExt01() == null : this.getExt01().equals(other.getExt01()))
            && (this.getExt02() == null ? other.getExt02() == null : this.getExt02().equals(other.getExt02()))
            && (this.getExt03() == null ? other.getExt03() == null : this.getExt03().equals(other.getExt03()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateBy() == null ? other.getLastUpdateBy() == null : this.getLastUpdateBy().equals(other.getLastUpdateBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_migration_task
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getTaskName() == null) ? 0 : getTaskName().hashCode());
        result = prime * result + ((getIsEnable() == null) ? 0 : getIsEnable().hashCode());
        result = prime * result + ((getIsEnableDelete() == null) ? 0 : getIsEnableDelete().hashCode());
        result = prime * result + ((getProcessing() == null) ? 0 : getProcessing().hashCode());
        result = prime * result + ((getLastExcuteTime() == null) ? 0 : getLastExcuteTime().hashCode());
        result = prime * result + ((getExt01() == null) ? 0 : getExt01().hashCode());
        result = prime * result + ((getExt02() == null) ? 0 : getExt02().hashCode());
        result = prime * result + ((getExt03() == null) ? 0 : getExt03().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateBy() == null) ? 0 : getLastUpdateBy().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_migration_task
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskId=").append(taskId);
        sb.append(", taskName=").append(taskName);
        sb.append(", isEnable=").append(isEnable);
        sb.append(", isEnableDelete=").append(isEnableDelete);
        sb.append(", processing=").append(processing);
        sb.append(", lastExcuteTime=").append(lastExcuteTime);
        sb.append(", ext01=").append(ext01);
        sb.append(", ext02=").append(ext02);
        sb.append(", ext03=").append(ext03);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", lastUpdateBy=").append(lastUpdateBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}