package com.github.support.entitement.mybatis.dao;

import com.github.support.entitement.mybatis.model.Bug;

public interface BugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bug
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bug
     *
     * @mbggenerated
     */
    int insert(Bug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bug
     *
     * @mbggenerated
     */
    int insertSelective(Bug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bug
     *
     * @mbggenerated
     */
    Bug selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bug
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bug
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Bug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bug
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bug record);
}