package com.github.support.entitement.mybatis.dao;

import com.github.support.entitement.mybatis.model.Resource;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated
     */
    Resource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Resource record);
}