package com.github.support.entitement.mybatis.dao;

import com.github.support.entitement.mybatis.model.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated
     */
    UserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRole record);
}