CREATE TABLE  if NOT EXISTS test.t_i18n (
  `I18N_KEY` varchar(100) NOT NULL,
  `I18N_LANG` varchar(16) NOT NULL,
  `DOMAIN_TYPE` varchar(100) NOT NULL DEFAULT '0',
  `I18N_CONTENT` varchar(100) DEFAULT NULL,
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATE_TYPE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`I18N_KEY`,`I18N_LANG`,`DOMAIN_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
