package com.github.support.entitement.mybatis.dao;

import com.github.support.entitement.mybatis.model.Online;

public interface OnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_online
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_online
     *
     * @mbggenerated
     */
    int insert(Online record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_online
     *
     * @mbggenerated
     */
    int insertSelective(Online record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_online
     *
     * @mbggenerated
     */
    Online selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_online
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Online record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_online
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Online record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_online
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Online record);
}