package com.github.support.mybatis.i18n.dao;

import com.github.support.mybatis.i18n.model.I18nBean;
import org.apache.ibatis.annotations.Param;

public interface I18nBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_i18n
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("i18nKey") String i18nKey, @Param("i18nLang") String i18nLang, @Param("domainType") String domainType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_i18n
     *
     * @mbggenerated
     */
    int insert(I18nBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_i18n
     *
     * @mbggenerated
     */
    int insertSelective(I18nBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_i18n
     *
     * @mbggenerated
     */
    I18nBean selectByPrimaryKey(@Param("i18nKey") String i18nKey, @Param("i18nLang") String i18nLang, @Param("domainType") String domainType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_i18n
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(I18nBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_i18n
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(I18nBean record);
}